[package]
name = "rfs-feox"
description = "Feox exokernel adapter: rfs-core BlockDevice over feox-nvme queue rings."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rfs-core = { path = "../rfs-core" }
feox-nvme = { git = "https://gitea.w-sky.net/rustcor/Feox.git" }

[lints]
workspace = true
